# Generated by Django 5.1 on 2024-08-31 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=20)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('preco', models.FloatField(max_length=9)),
                ('foto', models.ImageField(upload_to='AGECAR/fotos/')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carro_fabricante', to='agencia.fabricante')),
            ],
        ),
    ]
